# argocd-certificate.yml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-tls
  namespace: longhorn-system
spec:
  dnsNames:
    - longhorn.intranet.agride.xyz
  secretName: longhorn-tls
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
