apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-prod-intranet
  namespace: database
spec:
  instances: 3
  
  postgresql:
    parameters:
      max_worker_processes: "60"
    pg_hba:
      # To access through TCP/IP you will need to get username
      - host all all all md5
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
      additional:
      - selectorType: rw
        serviceTemplate:
          metadata:
            name: pg-prod-intranet-rw-lb
          spec:
            type: LoadBalancer
  storage:
    size: 1Gi