controller:
  service:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "Internal"
      networking.gke.io/load-balancer-type: "Internal"
    loadBalancerSourceRanges:
      - 10.0.0.0/8

grafana:
  adminUser: grafana
  adminPassword: grafana
