apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-prometheus-stack
    version: 73.2.2
    namespace: kube-prometheus-stack
    valuesFile: helm-values.yaml

resources:
  - namespace.yaml
