---
- name: Install Docker on Ubuntu
  hosts: all
  become: yes
  vars_prompt:
    - name: ansible_become_password
      prompt: "Enter sudo password"
      private: yes 
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages (ca-certificates and curl)
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create the /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.asc

    - name: Set correct permissions for the GPG key
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository to Apt sources
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Update apt cache again
      apt:
        update_cache: yes

    - name: Remove conflicting Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - make
        state: present
        
    - name: Download Docker Desktop .deb package
      get_url:
        url: https://desktop.docker.com/linux/main/amd64/docker-desktop-amd64.deb
        dest: /tmp/docker-desktop-amd64.deb

    - name: Install Docker Desktop from .deb file
      apt:
        deb: /tmp/docker-desktop-amd64.deb

    - name: Clean up downloaded .deb file
      file:
        path: /tmp/docker-desktop-amd64.deb
        state: absent