version: "3.8"

services:
  traefik:
    image: "traefik:v3.0"
    command:
      - "--providers.swarm.network=traefik-net"
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.metrics.address=:8082"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--log.level=DEBUG"

    ports:
      - "80:80"
      - "8082:8082"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - traefik-net

  app:
    image: maximebernarddata/app_image:latest 
    environment:
      APP_DEBUG: "false"
      APP_ENV: "dev"
      APP_KEY: "base64:DJYTvaRkEZ/YcQsX3TMpB0iCjgme2rhlIOus9A1hnj4="
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: app_database
      DB_USERNAME: app_user
      DB_PASSWORD: app_password
    
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.teststack_app.rule=HostRegexp(`.*`)"
        - "traefik.http.routers.teststack_app.entrypoints=web"
        - "traefik.http.services.teststack_app.loadbalancer.server.port=80"
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 5s
    networks:
      - traefik-net

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: app_root_password
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init/conf.d:/etc/mysql/conf.d:ro
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - traefik-net

volumes:
  db_data:

networks:
  traefik-net:
    external: true
