replicaCount: 2

image:
  repository: kubequest/sample-app
  tag: 0.0.4
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  APP_DEBUG: "true"
  APP_ENV: "prod"
  APP_KEY: "base64:DJYTvaRkEZ/YcQsX3TMpB0iCjgme2rhlIOus9A1hnj4="
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_DATABASE: app_database
  DB_USERNAME: app_user
  DB_PASSWORD: app_password

ingress:
  enabled: true
  enableTLS: true
  host: sample-app.spectrum-app.cloud
  tlsSecretName: sample-app-cert

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "1024Mi"  
    cpu: "750m"

mysql:
  enabled: true
  image: mysql:8.0
  rootPassword: app_root_password
  user: app_user
  password: app_password
  database: app_database
  port: 3306
  volumeSize: 1Gi

certManager:
  enabled: true
  issuerName: letsencrypt-prod
  acmeServer: https://acme-v02.api.letsencrypt.org/directory
  email: ber.maxime.paul@gmail.com  
  privateKeySecretName: letsencrypt-prod
  ingressClass: nginx



