apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-consul
  namespace: consul
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
