apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-consul
  namespace: consul
spec:
  storageClassName: longhorn
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/consul/data"
