- name: Mettre à jour /etc/hosts avec les IPs internes
  hosts: k8s
  become: true

  tasks:
    - name: Générer les lignes hosts avec IP VPC et rôles
      set_fact:
        k8s_hosts_entries: |
          {% for host in groups['k8s'] %}
          {{ hostvars[host]['k8s_ip'] }} {{ host }} {{ 'master' if host in groups['master'] else 'worker' }}
          {% endfor %}

    - name: Nettoyer les anciennes lignes des k8s-nodes (si existantes)
      lineinfile:
        path: /etc/hosts
        regexp: '^.*k8s-node-[0-9]+.*$'
        state: absent
      loop: "{{ groups['k8s'] }}"
      loop_control:
        loop_var: node

    - name: Ajouter le bloc hosts Kubernetes
      blockinfile:
        path: /etc/hosts
        block: "{{ k8s_hosts_entries }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - K8S CLUSTER HOSTS"
    - name: Activer le module br_netfilter
      become: true
      modprobe:
        name: br_netfilter
        state: present
    - name: Configurer les paramètres sysctl pour Kubernetes
      become: true
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
        mode: '0644'

    - name: Appliquer la configuration sysctl
      become: true
      command: sysctl --system

