{{- if .Values.cert.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.cert.name }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.cert.secretName }}
  issuerRef:
    name: {{ .Values.cert.issuer }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.cert.dnsName }}
{{- end }}