{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuerName }}
spec:
  acme:
    server: {{ .Values.certManager.acmeServer }}
    email: {{ .Values.certManager.email }}
    privateKeySecretRef:
      name: {{ .Values.certManager.privateKeySecretName }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.certManager.ingressClass }}
{{- end }}
