{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: {{ if .Values.ingress.enableTLS }}"true"{{ else }}"false"{{ end }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    {{- if and .Values.certManager.enabled .Values.ingress.enableTLS }}
    cert-manager.io/cluster-issuer: "{{ .Values.certManager.issuerName }}"
    {{- end }}
spec:
  ingressClassName: apps
{{- if .Values.ingress.enableTLS }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
