apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample-app-cert
  namespace: sample-app
spec:
  secretName: sample-app-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - sample-app.spectrum-app.cloud
