apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-runner-gitlab
  namespace: runner-gitlab
spec:
  storageClassName: longhorn
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/runner-gitlab"