apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-runner-gitlab
  namespace: runner-gitlab
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi