# argocd-certificate.yml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  dnsNames:
    - argocd.intranet.agride.xyz
  secretName: argocd-server-tls
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
