apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vault
  namespace: vault
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
