apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vault
  namespace: vault
spec:
  storageClassName: longhorn
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/vault"