apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  dnsNames:
    - vault.intranet.agride.xyz
  secretName: vault-tls
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
