---
# Source: mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-mysql
  namespace: "mysql"
  labels:
    app.kubernetes.io/instance: my-mysql
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: 9.3.0
    helm.sh/chart: mysql-13.0.1
    app.kubernetes.io/part-of: mysql
type: Opaque
data:
  mysql-root-password: "TWFkUDJkT1RmTg=="
  mysql-password: "QXg5WFJ2NWI4ZA=="
