apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysl-credentials
spec:
  refreshInterval: "15s" 
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mysql
    template:
      engineVersion: v2
      data:
        .env: |
          db_con="{{ .db_url }}"
          db_user="{{ .db_username }}"
          db_password="{{ .db_password }}"
       
  data:
  - secretKey: db_url
    remoteRef:
      key: mysql
      property: MYSQL_URL
  - secretKey: db_username
    remoteRef:
      key: mysql
      property:  MSQL_USER
  - secretKey: db_password
    remoteRef:
      key: mysql
      property: MYSQL_PWD