# issuer.yml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-clusterissuer
spec:
  acme:
    email: lucasantunes@free.fr
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-clusterissuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: lucasantunes@free.fr
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
