[project]
name = "gcp-stack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible>=11.6.0",
    "ansible-core>=2.18.6",
    "kubernetes>=33.1.0",
]
