project_id       = "kubequest-462618"
credentials_file = "credentials/terraform-sa.json"
create_vpc    = true
create_subnet = true
github_repo = "T-CLO-902-LYO_1"
github_token = "token"
github_user = "EpitechMscProPromo2025"
app_path = "helm/sample-app"
environnement= "prod"
ssh_user = "ubuntu"
ssh_key_path = "credentials/ssh-key"
public_key_path = "credentials/ssh-key.pub"